client/src/session_layer.rs
client/src/virtual_layer.rs
server/src/server.rs
server/tests/test_forwarding.rs

Pause / Resume forwarding - client side

---

client/src/lib.rs
server/Cargo.toml
server/readme.md
server/src/config.rs
server/src/lib.rs
server/src/main.rs
server/src/public_endpoints.rs
server/src/server.rs
server/src/testing/server.rs

resolves: https://github.com/golemfactory/ya-relay/issues/72

Configurable and constant public endpoint Discovery socket

---

client/src/client.rs
client/src/lib.rs
client/src/registry.rs
client/src/session_manager.rs
client/src/testing/forwarding_utils.rs
client/src/virtual_layer.rs
crates/proto/src/codec.rs
crates/proto/src/proto.rs
server/src/config.rs
server/src/server.rs
server/src/state.rs
server/src/testing/server.rs
server/tests/test_expired_session.rs

resolves: https://github.com/golemfactory/yagna/issues/1806
resolves: https://github.com/golemfactory/yagna/issues/1807
resolves: https://github.com/golemfactory/ya-relay/issues/87

Keep expired session for some period of time

---

crates/stack/src/device.rs

Fixes the current happy path flow by setting a very high MTU

Oversized MTU

---

Cargo.toml
client/src/session.rs
client/src/session_manager.rs
crates/proto/protobuf/ya_relay.proto
server/src/server.rs
server/tests/test_expired_session.rs

fixes: https://github.com/golemfactory/yagna/issues/1830

Send Disconnected message when getting forward from unknown session

---

crates/stack/src/connection.rs
crates/stack/src/lib.rs
crates/stack/src/patch_smoltcp.rs

maybe resolves: https://github.com/golemfactory/ya-relay/issues/94
maybe resolves: https://github.com/golemfactory/yagna/issues/1829

Implement get_socket_safe that doesn't panic

---

.github/workflows/rust.yml

Update windows version from 2019 to latest after fixes

---

client/src/registry.rs
client/src/session_manager.rs
client/src/virtual_layer.rs
crates/core/src/udp_stream.rs
crates/stack/src/device.rs
crates/stack/src/network.rs
crates/stack/src/socket.rs
crates/stack/src/stack.rs

Session re-initiation fixes

---

client/src/client.rs
client/src/virtual_layer.rs
crates/stack/src/lib.rs
crates/stack/src/network.rs
crates/stack/src/socket.rs
crates/stack/src/stack.rs

resolves: https://github.com/golemfactory/yagna/issues/1878
Requires updates in yagna

Configurable tcp buffer size multiplier relative to mtu

---

crates/stack/src/network.rs

resolves: https://github.com/golemfactory/yagna/issues/1877
Requires yagna update

Remove data chunking in Network

---

client/src/session_manager.rs

resolves: https://github.com/golemfactory/yagna/issues/1880

Close all sessions at the same time

---

client/src/client.rs
client/src/session.rs
client/src/session_manager.rs
client/src/virtual_layer.rs
crates/core/src/udp_stream.rs
crates/stack/src/lib.rs
crates/stack/src/network.rs
crates/stack/src/socket.rs

- warn while sending packets of size greater than current soft max

Session and socket inspection interface

---

server/src/server.rs

Registering endpoints requires public endpoints check, which can last a few seconds if any Node is unreachable.
If new packet comes, it can block server, since channel has only 1 element.
Resolves: https://github.com/golemfactory/ya-relay/issues/129

Spawn sending initialization packets to channel

---

client/src/session_manager.rs

resolves: https://github.com/golemfactory/yagna/issues/1977

Register p2p sessions on incoming connection

---

client/Cargo.toml
client/examples/client.rs
client/examples/saturate.rs
client/src/client.rs
client/src/expire.rs
client/src/session.rs
client/src/testing/forwarding_utils.rs
client/src/virtual_layer.rs
crates/core/Cargo.toml
crates/core/src/udp_stream.rs
crates/proto/Cargo.toml
crates/proto/src/codec.rs
crates/proto/src/lib.rs
crates/stack/Cargo.toml
crates/stack/src/network.rs
server/Cargo.toml
server/src/main.rs
server/tests/test_broadcasts.rs
server/tests/test_expired_session.rs
server/tests/test_forwarding.rs
server/tests/test_reverse_connection.rs

partially resolves: https://github.com/golemfactory/yagna/issues/1326

Update tokio; fix tests

---

client/src/session.rs
client/src/session_manager.rs
client/src/session_start.rs
client/src/virtual_layer.rs
crates/core/src/lib.rs
crates/core/src/sync.rs
crates/stack/src/network.rs

- forwarding is paused and resumed per session
- forwarding is paused for inbound sessions; resuming is now a part of session initialization

Pause forwarding per session

---

client/Cargo.toml
client/src/dispatch.rs
client/src/session.rs
client/src/session_guard.rs
client/src/session_manager.rs
client/src/session_start.rs
client/src/virtual_layer.rs
crates/core/src/lib.rs
crates/core/src/sync.rs
crates/stack/src/network.rs

Remember to retarget branch to main.
resolves: https://github.com/golemfactory/ya-relay/issues/147
resolves: https://github.com/golemfactory/yagna/issues/2015
resolves: https://github.com/golemfactory/ya-relay/issues/149
+ Log improvments

Fix connections issues

---

client/src/session_manager.rs
client/src/session_start.rs

resolves: https://github.com/golemfactory/ya-relay/issues/150

Check if session with Node exists under guard

---

client/src/registry.rs
client/src/session_manager.rs
client/src/session_start.rs
client/src/virtual_layer.rs
crates/proto/src/codec/forward.rs
crates/proto/src/proto.rs

- increase session manager forward log level to default
- remote id validation
- minor cosmetic (and not so cosmetic) changes

Session state tracking

---

server/Cargo.toml
server/src/config.rs
server/src/main.rs
server/src/metrics.rs
server/src/server.rs
server/src/testing/server.rs

fixes: https://github.com/golemfactory/golem-internal/issues/434

Http metrics listener

---

crates/core/Cargo.toml
crates/core/src/utils.rs
server/src/server.rs
server/tests/test_expired_session.rs

The server was unable to listen on an IPv6 address

Server IPv6 compat fix

---

crates/stack/src/network.rs
crates/stack/src/stack.rs

- skip the remaining steps of `network.poll` based on the hint form `stack.poll`
- fixed stack poller interval, configurable via an env variable

Poll tweaks

---

client/src/client.rs

Adds a node lookup function for CLI interaction

Client::find_node

---

client/examples/saturate.rs
client/src/client.rs
client/src/lib.rs
client/src/session_manager.rs
client/src/virtual_layer.rs
crates/core/Cargo.toml
crates/core/src/session.rs
crates/proto/src/codec.rs
crates/proto/src/lib.rs
crates/stack/src/metrics.rs
server/src/server.rs

resolves: https://github.com/golemfactory/yagna/issues/2172
required for: https://github.com/golemfactory/yagna/pull/2168
Additional changes:
- Query per session transfer metrics

Experimental implementation of transfer socket

---

client/src/registry.rs
client/src/session_manager.rs
server/src/state.rs
server/tests/test_discovery.rs

Based on https://github.com/golemfactory/ya-relay/pull/203
Resolves https://github.com/golemfactory/yagna/issues/2189

Fix node alias handling

---

server/tests/test_discovery.rs

reproduction of: https://github.com/golemfactory/yagna/issues/2189

Test reproducing problem with communication to alias Node

---

crates/core/Cargo.toml

resolves: https://github.com/golemfactory/golem-internal/issues/503

Update ya-client-model to version v0.5

---

client/src/expire.rs

it fixes https://github.com/golemfactory/golem-internal/issues/523

drop srv session if not responding to ping

---

server/src/server.rs

For debugging issue #222, may be reverted after it's fixed.

Add debug logs in packet dispatch

---

client/src/virtual_layer.rs
crates/stack/src/connection.rs
crates/stack/src/network.rs
crates/stack/src/socket.rs
crates/stack/src/stack.rs

resolves: https://github.com/golemfactory/yagna/issues/2507

Improve network

---

client/src/session_manager.rs
server/Cargo.toml
server/tests/test_closed_session.rs

Resolves [#2387](https://github.com/golemfactory/yagna/issues/2387)

Node identities removing together with aliases.

---

client/examples/http_client.rs
tests/test_net_down.py

Resolves [#296](https://github.com/golemfactory/ya-relay/issues/296)
Http client handling multiple msgs in Fwd payload. 
Test with pending ping in background and pinged client reconnecting to network.

Http client handling multiple msgs in Fwd payload.

---

test_env/Dockerfile.base
test_env/Dockerfile.client
tests/conftest.py
tests/docker-compose.yml
tests/shared/utils.py
tests/test_priv_net.py

Resolves: https://github.com/golemfactory/ya-relay/issues/309

Integration test clients behind NAT

---

client/src/session.rs
test_env/README.txt
test_env/basic-setup.sh
test_env/build.sh
test_env/nat-clients-setup.sh
test_env/scenario-net-down.sh

Improve example scripts

---

client/src/session.rs
client/src/session/session_initializer.rs
tests_integration/README.md

remove unnecessary async

---

tests_integration/test_sessions.py

Test as a result of investigating #276

Simultaneous session initialization test

---

server/Cargo.toml
server/src/udp_server/socket.rs

There is a mismatch of types in [glibc](https://github.com/rust-lang/libc/blob/main/src/unix/linux_like/linux/gnu/mod.rs#L98) and [musl](https://github.com/rust-lang/libc/blob/main/src/unix/linux_like/linux/musl/b64/mod.rs#L104)

conditional compilation for musl
