golemfactory/ya-relay

crates/core/src/utils.rs

`utils::parse_node_id` is susceptible of failing to infer the type of `NodeId::default().as_ref()` :
```
22 |     if id.len() != NodeId::default().as_ref().len() {
|                    ------------------^^^^^^--
|                    |                 |
|                    |                 cannot infer type for type parameter T declared on the trait AsRef
|                    this method call resolves to &T
|
= note: type must be known at this point
```
The described case is common while developing changes to `ya-client` while using `ya-relay` as a dependency (e.g. in `yagna`). This PR fixes the issue by introducing explicit types

Explicitly typed `NodeId` byte ref

---

client/Cargo.toml
client/examples/client.rs
client/src/client.rs
client/src/registry.rs
client/src/session.rs
client/src/session_manager.rs
client/src/virtual_layer.rs
crates/core/Cargo.toml
crates/core/src/lib.rs
crates/core/src/utils.rs
server/Cargo.toml
server/src/server.rs
server/src/state.rs
server/tests/test_broadcasts.rs
server/tests/test_init_session.rs

~~**Requires https://github.com/golemfactory/ya-client/pull/117 to be merged first!**~~ 👍 
- grouped imports of ya-client-model into `crates/core`, no accidental wrong versions
- export NodeId from the core crate
- removed `parse_node_id`
- added `TryFrom<&Vec<u8>> for NodeId` in ya-client

use TryFrom &Vec<u8> feature on NodeId

---

client/src/client.rs
client/src/dispatch.rs
client/src/expire.rs
client/src/lib.rs
client/src/registry.rs
client/src/session.rs
client/src/session_layer.rs
client/src/session_manager.rs
client/src/session_start.rs
client/src/testing.rs
client/src/testing/forwarding_utils.rs
client/src/virtual_layer.rs
crates/core/src/lib.rs
crates/proto/protobuf/ya_relay.proto
crates/proto/src/proto.rs
crates/stack/src/connection.rs
crates/stack/src/interface.rs
crates/stack/src/network.rs
crates/stack/src/stack.rs
server/Cargo.toml
server/src/config.rs
server/src/public_endpoints.rs
server/src/server.rs
server/src/testing/server.rs
server/tests/test_expired_session.rs
server/tests/test_forwarding.rs
server/tests/test_init_session.rs

resolves: https://github.com/golemfactory/ya-relay/issues/64
This PR doesn't solve problems fully
Changes:
- Closing expired p2p sessions
- Setting NodeId as MAC address on Ethernet layer to preserve addresses across 2 client executions
- Fixes to closing connection in Tcp stack
- Make most of the relay server constants configurable
- Server sends `Disconnected` message, when forwarding to expired Node

Handling expired sessions

---

client/src/session_manager.rs

This PR consists of new function for checking if p2p connection exists for given `NodeId`. The function is used in `yagna` for hybrid net metrics implementation (this is related to issue https://github.com/golemfactory/yagna/issues/1796). Please merge this PR before merging [that ](https://github.com/golemfactory/yagna/pull/1835) one.

checking if p2p_connection exists

---

client/src/session.rs
client/src/session_manager.rs
crates/core/src/error.rs
server/src/server.rs

resolves: https://github.com/golemfactory/ya-relay/issues/66
Don't merge after final decision.
This solution should make disconnections more graceful, but NET should handle cases, when message isn't reaching it's target
Todo:

Disconnect on shutdown

---

client/src/session_manager.rs
client/src/session_start.rs
crates/core/src/challenge.rs
crates/core/src/session.rs
crates/proto/protobuf/ya_relay.proto
crates/proto/src/codec/datagram.rs
crates/proto/src/codec/stream.rs
crates/proto/src/proto.rs
server/src/server.rs

Session::Request, Session::Response and NodeInfo
Resolves: https://github.com/golemfactory/yagna/issues/1857

First step in adding encryption: 

---

crates/stack/src/network.rs
crates/stack/src/socket.rs

When a remote peer connects to a local listening socket, that listening socket is moved to another (connected) state. Logic inside the network module is responsible for re-creating the listening socket. This PR fixes a situation where such socket was not properly re-bound, resulting in stalled transmission / no possibility to establish new connections

Strict socket re-binding

---

server/src/server.rs

For server debugging purposes.
Additionally, unify state read lock acquisition in server.

Log session cleanup completion

---

client/src/client.rs
client/src/session_manager.rs

- do not disconnect P2P nodes on neighborhood change
- drop duplicate `has_p2p_connection`
NOTE: this PR is targeting `mf/multiple-identities`

Restart server session API

---

client/src/dispatch.rs
client/src/session_manager.rs

- adds a possibility to register session-wide response error handlers
- registers an `Unauthorized` error handler for relay server sessions (server session re-initiation)

Session error handlers

---

crates/stack/src/packet.rs

The check is not mandatory and does not account packet fragmentation in

Fix IP4 packet peek for fragmented packets

---

client/src/lib.rs

A collection of `SessionDesc` is returned by `Client.sessions`, but the type itself is not exported by the `ya-relay-client` module

Export session descriptor struct

---

crates/core/src/error.rs
server/src/server.rs

Clients receiving the Unauthorized error will try to re-initiate server sessions
- allow `Disconnected` messages for unknown sessions
- remove `BadRequest::SessionNotFound` variant

Server: return unauthorized if session is not known

---

server/src/server.rs

It fixes https://github.com/golemfactory/ya-relay/issues/155

ignore ResumeForwarding control packet when dispatching

---

crates/stack/src/network.rs

Without polling the stack, the bound socket may not enter the `LISTENING` state

Poll the stack while re-binding a socket in `process_ingress`

---

client/Cargo.toml
client/examples/saturate.rs

- option for periodically dumping sampled data into a CSV file
- option for running the receiver and sender for a specified amount of time
- customizable csv and log output directory

Export to CSV in `saturate` example

---

crates/stack/src/network.rs

Limits the total bytes of egress payload that can be processed at once,
so that ingress packets (e.g. ACKs) can be processed on time.

Interleaved ingress and egress packet processing

---

crates/stack/Cargo.toml

Includes the change in https://github.com/golemfactory/smoltcp/commit/acb743b6990fd92303c24c43ff75711422a5cb94

(smoltcp) fix data_range overflow in AssemblerIter

---

client/src/dispatch.rs
client/src/session.rs
crates/core/src/session.rs
server/src/server.rs
server/src/state.rs

1. The client sends the same request up to 4 times in `timeout / 4` intervals.
2. The server ignores duplicate requests, and the client ignores duplicate responses.
3. Tune `DISPATCH_TASK_COUNT` to 32.
Closes https://github.com/golemfactory/yagna/issues/1872.

Repeat protocol messages

---

.github/workflows/rust.yml
client/src/session_manager.rs
crates/stack/src/stack.rs

P2P connections might cause clients to send duplicate requests not only to the relay (already handled correctly), but also to other clients. This has caused deadlocks while establishing a reverse connection.

Deduplicate incoming requests in ya-relay-client

---

.github/workflows/release.yml

It resolves this Release build failure https://github.com/golemfactory/ya-relay/actions/runs/6254512421/job/16982209231
(it is caused by converting `ya-relay` to a package)

Release build fix

---

client/examples/http_client.rs
client/src/client.rs

When requesting neighbourhood information, the client can select if it is interested in the public key of the nodes.
Prior to the 'redesign idea' the server did not return any identity for the nodes when the public key was not requested, the client always requested the public key.
This was 'fixed' during the 'redesign idea' changes so the client does not request the public key and the server send back the identities with empty public key.
Unfortunately this is not backward compatible and the new client does not work with the previous server version (it would work the other way around, new server - previous client) as it gets node information without identities so it is not usable for neighbourhood brodcasting.

Neighbourhood fix

---

client/src/session/session_initializer.rs

If `num_cpus::get()` returns 1 then an overflow occurs

prevent overflow
